DjangoBlog/DjangoBlog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views #django系统自带的login/logout
from django.urls import path, include
from django.conf import settings       # for upload image 只适用于开发环境
from django.conf.urls.static import static # for upload image 只适用于开发环境
from users import views as users_views  #users应用的views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',users_views.register,name='register'),  # 用户注册
    path('profile/',users_views.profile,name='profile'), # 用户profile
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),    # 用户登录
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'), # 用户注销
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'), # 请求重置密码
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'), # 执行重置密码，发送密码
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'), # 确认重置密码，设置新密码
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'), # 设置新密码完成
    path('', include('blog.urls', namespace='blog')) #默认首页 namespace='blog'指定实例名blog
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoBlog/blog/urls.py
from django.urls import path
from . import views

# 使用通用视图
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    UserArticleListView,
    CategoryListView,
    TagListView
)

app_name = 'blog'  #定义应用程序的命名空间(访问路由地时候可以用“应用命名空间：路由name”)

urlpatterns = [
    #path('', views.index, name='root'), 
    #path('index/', views.index, name='index'),
    #path('detail/<int:id>',views.detail,name='detail'),
    #path('articles/category/<int:category_id>',views.category,name='category'),
    #path('articles/tag/<str:tag_name>',views.tag, name='tag')
    path('', ArticleListView.as_view(), name='root'),   # 使用通用视图    
    path('index/', ArticleListView.as_view(), name='index'),    # 使用通用视图
    path('about/',views.about,name='about'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),   # 使用通用视图
    path('detail/new/', ArticleCreateView.as_view(), name='create'),   # 使用通用视图
    path('detail/<int:pk>/update/', ArticleUpdateView.as_view(), name='update'),   # 使用通用视图
    path('detail/<int:pk>/delete/', ArticleDeleteView.as_view(), name='delete'),   # 使用通用视图
    path('articles/user/<str:username>',UserArticleListView.as_view(),name='userarticlelist'),  # 使用通用视图
    path('articles/category/<int:category_id>',CategoryListView.as_view(),name='category'),
    path('articles/tag/<str:tag_name>',TagListView.as_view(), name='tag')
]  

DjangoBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse   # URL反向函数，返回一个绝对地址的URL字符串

# Create your models here.

class Tag(models.Model):
    name = models.CharField(u'文章标签', max_length=30)

    class Meta:        
        verbose_name = u"文章标签"   #模型类的可读名称
        verbose_name_plural = verbose_name  #模型类的可读名称的复数形式 eg. xxx+s

    def __str__(self):
        """
        返回model对象自身
        """
        return self.name

class Category(models.Model):
    name = models.CharField(u'文章类型', max_length=30)

    class Meta:
        ordering = ['name']         #排序
        verbose_name = u"文章类型"   #模型类的可读名称
        verbose_name_plural = verbose_name  #模型类的可读名称的复数形式 eg. xxx+s

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(verbose_name=u'标题',max_length=200)    #文章标题
    digest = models.TextField(verbose_name=u'摘要', blank=True, null=True)  # 文章摘要
    picture = models.CharField(max_length=200)  # 文章标题的配图地址
    content = models.TextField(verbose_name=u'正文', blank=True, null=True)  # 正文
    created_date = models.DateField(verbose_name=u'创建日期',auto_now_add=True)  # 博客创建日期
    last_mod_date = models.DateTimeField(auto_now=True) # 博客修改日期
    author = models.ForeignKey(User, verbose_name=u'作者', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name=u'类型', on_delete=models.CASCADE)  #分类，一对一
    tag = models.ManyToManyField(Tag,verbose_name=u'标签')  # 标签，多对多
    view = models.BigIntegerField(verbose_name=u'阅读量',default=0)  # 阅读数
    comment = models.BigIntegerField(verbose_name=u'评论数',default=0)  # 评论数

    class Meta:  # 按时间降序
        ordering = ['-created_date']
        verbose_name = u"文章"   #模型类的可读名称
        verbose_name_plural = verbose_name  #模型类的可读名称的复数形式 eg. xxx+s

    def __str__(self):
        return self.title
    
    def viewed(self):
        """
        增加阅读量函数
        """
        self.view += 1
        self.save(update_fields=['view'])
    
    def commenced(self):
        """
        增加评论数
        :return:
        """
        self.comment += 1
        self.save(update_fields=['comment'])
    
    # 给通用模板处理返回一个绝对地址的URL字符串
    # 发布博文后，应用会自动重定向到该URL
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

class CarouselImg(models.Model):
    title = models.CharField(verbose_name=u'标题', max_length=200)    # 轮播图的标题    
    #上传路径到：carousel_pics
    image = models.ImageField(verbose_name=u'图片', upload_to='carousel_pics') # 轮播图

    class Meta:
        verbose_name = u"轮播图"   #模型类的可读名称
        verbose_name_plural = verbose_name  #模型类的可读名称的复数形式 eg. xxx+s
    
    def __str__(self):
        return self.title

DjangoBlog/blog/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required #只有已经登录的用户才能访问视图
from .models import Tag, Category, Article

# 使用通用视图
from django.views.generic import (
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
# 个别通用视图类访问前必须先登录，如果没有登录，重定向到登录页面
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib import messages

# Create your views here.
def about(request):
    """
    blog的about页
    @param request
    @return 'blog/about.html'
    """
    output = '这是blog的about页面'
    return HttpResponse(output)

# 使用通用视图，比起传统的函数方式，django对通用视图有很多后台处理
# 只需要简单变量设置
class ArticleListView(ListView):
    model = Article
    template_name = 'blog/index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'article_list'    #模板中使用的上下文变量名
    ordering = ['-last_mod_date']
    paginate_by = 5 #分页，设置每页显示的博文个数


class ArticleDetailView(DetailView):
    model = Article   
    template_name = 'blog/detail.html'

    # 覆写 get_object 方法的目的是因为需要对 Article 的 点击量的值进行更新
    def get_object(self, queryset=None):        
        article = super(ArticleDetailView, self).get_object(queryset=None)
        article.viewed()
        return article    

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ['title', 'digest', 'content', 'category','tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request,f'成功创建博文!')
        return super().form_valid(form)   

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ['title', 'digest', 'content', 'category','tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request,f'成功更新博文!')
        return super().form_valid(form)

    # 检查请求更新博文的用户是否是作者
    def test_func(self):
        Article = self.get_object()
        if self.request.user == Article.author:
            return True
        return False

class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    success_url = '/'

    # 检查请求删除博文的用户是否是作者
    def test_func(self):
        Article = self.get_object()        
        if self.request.user == Article.author:            
            return True
        return False

class UserArticleListView(ListView):
    model = Article
    template_name = 'blog/articles.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'article_list'    #模板中使用的上下文变量名
    paginate_by = 5 #分页，设置每页显示的博文个数

    def get_queryset(self):
        article_list= Article.objects.filter(author__username = self.kwargs['username']).order_by('-last_mod_date') #从self.kwargs中（即，从url参数中）获取用户名
        return article_list

class CategoryListView(ListView):
    model = Article
    template_name = 'blog/articles.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'article_list'    #模板中使用的上下文变量名
    paginate_by = 5 #分页，设置每页显示的博文个数

    def get_queryset(self):
        article_list= Article.objects.filter(category_id = self.kwargs['category_id']).order_by('-last_mod_date')    
        return article_list

class TagListView(ListView):
    model = Article
    template_name = 'blog/articles.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'article_list'    #模板中使用的上下文变量名
    paginate_by = 5 #分页，设置每页显示的博文个数
    def get_queryset(self):
        article_list= Article.objects.filter(tag__name = self.kwargs['tag_name']).order_by('-last_mod_date')
        return article_list

DjangoBlog/templates/blog/article_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
<div>            
    <form method="POST" role="form">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">删除博文</legend>
            <h2>确定要删除博文 "{{ object.title }}" 吗？ </h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-danger"　type="submit">是的，删除</button>
            <a class="btn btn-primary" href="{% url 'blog:detail' object.id %}">取消</a>
        </div>
    </form>   
</div>    
{% endblock %}

DjangoBlog/templates/blog/article_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div>            
    <form method="POST" role="form">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">创建博文</legend>            
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-primary btn-outline-info"　type="submit">发布</button>
        </div>
    </form>   
</div>    
{% endblock %}

DjangoBlog/templates/blog/articles.html
<!--按照Category,Tag分类后的博文列表-->
{% extends "blog/base.html" %}
{% block content %}
{% load static %}
<!--博文列表-->
<div class="article-list">
    <h1 class="mb-3">博文数:{{ page_obj.paginator.count }}</h1>
    {% for article in article_list %}
    <article class="article-item">
        <a href="{% url 'blog:userarticlelist' article.author.username %}" class="avatar">
            <img class="rounded-circle account-img" src="{{ article.author.profile.image.url }}" alt="author-image">
        </a>
        <div class="article-item-main">
            <div class="article-item-info">
                <a href="{% url 'blog:userarticlelist' article.author.username %}"
                    class="author-name">{{ article.author.username }}</a>
                <a href="{% url 'blog:detail' article.id %}" class="date-and-source">
                    <span class="glyphicon glyphicon glyphicon-time"></span>{{ article.created_date }}
                </a>
                <a href="{% url 'blog:category' category_id=article.category_id %}" class="date-and-source">
                    <span class="glyphicon glyphicon-th-large"></span>{{ article.category }}
                </a>
            </div>
            <div class="article-item-body">
                <div class="article-item-content">
                    <a href="{% url 'blog:detail' article.id %}">
                        <h3 class="article-title">{{ article.title }}</h3>
                    </a>
                    <div class="article-content">{{ article.digest }}</div>
                </div>
            </div>
            <div class="article-item-footer">
                <a href="#" class="article-item-control">
                    <span class="glyphicon glyphicon glyphicon-eye-open"></span>{{ article.view }}
                </a>
                <a href="#" class="article-item-control">
                    <span class="glyphicon glyphicon glyphicon-comment"></span>{{ article.comment }}
                </a>
            </div>
        </div>
    </article>
    {% endfor %}

    {% if is_paginated %}
        
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">首页</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">上一页</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>          
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">下一页</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">末页</a>
        {% endif %}

    {% endif %}
</div>
{% endblock %}

DjangoBlog/templates/blog/detail.html
<!--博文详细画面-->
{% extends "blog/base.html" %}
{% block content %}
<!--引入markdown标签-->
{% load markdown_deux_tags %}
<!--博文详细-->
<article class="article-item">
        <a href="{% url 'blog:userarticlelist' article.author.username %}" class="avatar">
            <img class="rounded-circle account-img" src="{{ object.author.profile.image.url }}" alt="author-image">
        </a>
        <div class="article-item-main">
            <div class="article-item-info">
                <a href="{% url 'blog:userarticlelist' article.author.username %}" class="author-name">{{ object.author.username }}</a>
                <a href="{% url 'blog:detail' article.id %}" class="date-and-source">
                    <span class="glyphicon glyphicon glyphicon-time"></span>{{ object.created_date }}
                </a>
                <a href="{% url 'blog:category' category_id=article.category_id %}" class="date-and-source">
                    <span class="glyphicon glyphicon-th-large"></span>{{ object.category }}
                </a>
                {% if object.author == user %}
                    <div class="article-item-btn">
                        <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'blog:update' object.id %}" title="更新博文">更新</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:delete' object.id %}" title="删除博文">删除</a>
                    </div>                    
                {% endif %}
            </div>
            <div class="article-item-body">
                <div class="article-item-content">                        
                    <a href="{% url 'blog:detail' article.id %}">
                        <h2 class="article-title">{{ object.title }}</h2>
                    </a>
                    <div class="article-content">{{ object.content | markdown }}</div>                        
                </div>
            </div>
            <div class="article-item-footer">
                <a href="#" class="article-item-control">
                    <span class="glyphicon glyphicon glyphicon-eye-open"></span>{{ object.view }}
                </a>
                <a href="#" class="article-item-control">
                    <span class="glyphicon glyphicon glyphicon-comment"></span>{{ object.comment }}
                </a>
            </div>
        </div>
</article>
{% endblock %}

DjangoBlog/templates/blog/footer.html
<!--footer-->

<div style="text-align: center;">
  <p>CopyRight &#169; 2019-2020 阿尔布斯的雪的博客 &#160;&#160;&#160; designed by AlpsSnow</p>
</div>
<!-- /top-link-block -->
<a id="back-to-top" href="#" class="btn btn-info btn-lg back-to-top" role="button" title="Top" data-toggle="tooltip"
  data-placement="left">
  <span class="glyphicon glyphicon-chevron-up"></span>
</a>

DjangoBlog/templates/blog/header.html
{% load static %}
<div container >
    <nav class="navbar navbar-default" role="navigation">
        <div class="row">
            <div class="hidden-xs col-sm-2 col-md-2 col-lg-2" style="padding: 15px;">
                <img src="{% static 'blog/image/AlpsSnow.logo.png' %}" alt="logo">
            </div>
            <div class="hidden-xs hidden-sm col-md-2 col-lg-2 text-primary" style="padding: 15px;">
                通知：今天特别放假一天
            </div>
            <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#example-navbar-collapse">
                        <span class="sr-only">切换导航</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#" style="color: #5bc0de;">阿尔卑斯的雪</a>
                </div>
                <div class="collapse navbar-collapse" id="example-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li ><a href="{% url 'blog:index' %}" style="color: #5bc0de;">首页</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #5bc0de;">
                                分类 <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                {% for category in category_list %}
                                    <li>
                                        <a href="{% url 'blog:category' category_id=category.id %}" style="color: #5bc0de;">
                                            <span>{{ category.name }}</span>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li><a href="{% url 'blog:about'%}" style="color: #5bc0de;">关于</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!--判断用户是否已经登录？-->
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'blog:create' %}" style="color: #5bc0de;"><span class="glyphicon glyphicon-plus"></span>发布</a></li>
                            <li><a href="{% url 'profile' %}" style="color: #5bc0de;"><span class="glyphicon glyphicon-credit-card"></span>个人信息</a></li>
                            <li><a href="{% url 'logout' %}" style="color: #5bc0de;"><span class="glyphicon glyphicon-log-out"></span>注销</a></li>
                        {% else %}
                            <li><a href="{% url 'register' %}" style="color: #5bc0de;"><span class="glyphicon glyphicon-user"></span>注册</a></li>
                            <li><a href="{% url 'login' %}" style="color: #5bc0de;"><span class="glyphicon glyphicon-log-in"></span>登录</a></li>
                        {% endif %}
                    </ul>
                </div>

            </div>
            <div class="hidden-xs hidden-sm hidden-md col-lg-2">
                <!--最右侧保留-->                
            </div>
        </div>
    </nav>
</div>

DjangoBlog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}
<div>
    <!--轮播图-->
    <div id="blogCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
        <!--轮播(carousel)图标题-->
        <ol class="carousel-indicators">
            {% for carouselimg in carouselimg_list %}
            {% if forloop.first %}
            <li data-target="#blogCarousel" data-slide-to="{{ carouselimg.pk }}" class="active"></li>
            {% else %}
            <li data-target="#blogCarousel" data-slide-to="{{ carouselimg.pk }}"></li>
            {% endif %}
            {% endfor %}
        </ol>
        <!--轮播(carousel)图项目-->
        <div class="carousel-inner">
            {% for carouselimg in carouselimg_list %}
            {% if forloop.first %}
            <div class="item active">
                {% else %}
                <div class="item">
                    {% endif%}
                    <img class="img-responsive" src="{{ carouselimg.image.url }}" alt="{{ carouselimg.title }}">
                    <div class="carousel-caption">{{ carouselimg.title }}</div>
                </div>
                {% endfor %}
            </div>
            <!--轮播(carousel)图按钮-->
            <a class="left carousel-control" href="#blogCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#blogCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="article-list">
        {% for article in article_list %}
        <article class="article-item">
            <a href="{% url 'blog:userarticlelist' article.author.username %}" class="avatar">
                <img class="rounded-circle account-img" src="{{ article.author.profile.image.url }}" alt="author-image">
            </a>
            <div class="article-item-main">
                <div class="article-item-info">
                    <a href="{% url 'blog:userarticlelist' article.author.username %}" class="author-name">{{ article.author.username }}</a>
                    <a href="{% url 'blog:detail' article.id %}" class="date-and-source">
                        <span class="glyphicon glyphicon glyphicon-time"></span>{{ article.created_date }}
                    </a>
                    <a href="{% url 'blog:category' category_id=article.category_id %}" class="date-and-source">
                        <span class="glyphicon glyphicon-th-large"></span>{{ article.category }}
                    </a>
                </div>
                <div class="article-item-body">
                    <div class="article-item-content">                        
                        <a href="{% url 'blog:detail' article.id %}">
                            <h2 class="article-title">{{ article.title }}</h2>
                        </a>
                        <div class="article-content">{{ article.digest }}</div>                        
                    </div>
                </div>
                <div class="article-item-footer">
                    <a href="#" class="article-item-control">
                        <span class="glyphicon glyphicon glyphicon-eye-open"></span>{{ article.view }}
                    </a>
                    <a href="#" class="article-item-control">
                        <span class="glyphicon glyphicon glyphicon-comment"></span>{{ article.comment }}
                    </a>
                </div>
            </div>
        </article>
        {% endfor %}

        {% if is_paginated %}
        
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">首页</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>          
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">下一页</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">末页</a>
        {% endif %}

        {% endif %}
    </div>
{% endblock %}

DjangoBlog/templates/blog/right.html
<!--关注我-->
{% load static %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">关注我</h3>
    </div>
    <div class="panel-body">
        panel 类容
    </div>
</div>

<!--新闻资讯-->
<div class="panel panel-default news">
    <div class="panel-heading">
        <h3 class="panel-title">资讯</h3>
    </div>
    <div class="panel-body">
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                    src="http://i.tianqi.com/index.php?c=code&a=getcode&id=34&h=25&w=280">
                </iframe>
            </li>
            <li><i class="el-calendar"></i>历史今天：
                <iframe
                    src="http://www.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                    width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true">
                </iframe>
            </li>
        </ul>
    </div>
</div>

<!--搜索-->

<!--文章排行-->

<!--标签-->
<div class="panel panel-default tags">
    <div class="panel-heading">
        <h3 class="panel-title">云标签</h3>
    </div>
    <div class="panel-body" id="tags-panel-body">
        <ul>
            {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag_name=tag.name %}" title="标签：{{ tag.name }} ">
                    <span class="label tags_labe">{{ tag.name }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<!--友情链接-->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">友情链接</h3>
    </div>
    <div class="panel-body">
        panel 类容
    </div>
</div>

<script type="text/javascript">
    var tagslabes = document.getElementsByClassName('tags_labe');
    var labesclass = new Array()
    labesclass[0] = "label-default"
    labesclass[1] = "label-primary"
    labesclass[2] = "label-success"
    labesclass[3] = "label-info"
    labesclass[4] = "label-warning"
    labesclass[5] = "label-danger"
    var n = 0;

    for (let i = 0; i < tagslabes.length; i++) {
        if (n === 6) {
            n = 0;
        }
        tagslabes[i].classList.add(labesclass[n]);
        n++;        
    }

</script>